version: '3.8'

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
        - "C:/QA_AUTOMATION/docker-example/init/selenoid:/etc/selenoid"
        - "${PWD}/work/selenoid/video:/opt/selenoid/video"
        - "${PWD}/work/selenoid/logs:/opt/selenoid/logs"
        - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=work/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
    network_mode: bridge
  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    links:
    - selenoid
    ports:
    - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ${PWD}/work/jenkins:/var/jenkins_home
    ports:
      - 8000:8080
    network_mode: bridge




